version: 2.1

orbs:
  change-api: financial-times/change-api@0.24.0

references:
  workspace_root: &workspace_root
    ~/project/

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - v1-dependency-npm-{{ checksum "package-lock.json" }}-
        - v1-dependency-npm-{{ checksum "package-lock.json" }}
        - v1-dependency-npm-

  cache_node_modules: &cache_node_modules
    save_cache:
      key: v1-dependency-npm-{{ checksum "package-lock.json" }}-{{ epoch }}
      paths:
        - ./node_modules/

executors:
  node:
    docker:
      - image: circleci/node:10-browsers
  python-node:
    docker:
      - image: circleci/python:3.7-node

jobs:
  install:
    executor: node
    steps:
      - checkout

      - *restore_node_modules

      - run:
          name: Install npm dependencies
          command: npm install --no-save

      - *cache_node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .

  verify:
    executor: node
    steps:
      - *attach_workspace

      - run:
          name: verify
          command: make verify -j 4


  release_prod:
    executor: python-node
    steps:
      - *attach_workspace

      - run:
          name: Install AWS CLI
          command: sudo pip install awscli

      - deploy:
          name: Serverless deploy prod
          command: make prod-env && ./node_modules/@financial-times/rel-engage/packages/circleci/do-exclusively.sh --branch $CIRCLE_BRANCH make deploy

      - run:
          name: Monitor dependencies for security vulnerabilities
          command: make security-monitor

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - install
      - verify:
          context: rel-eng-creds
          requires:
            - install
      - release_prod:
          context: rel-eng-creds
          requires:
            - verify
          filters:
            branches:
              only: master
      - change-api/release-log:
          name: release-log_prod
          context: rel-eng-creds
          requires:
            - release_prod
          systemCode: "github-active-users"
          slackChannels: rel-eng-changes
          environment: "prod"
          filters:
            branches:
              only: master

experimental:
  notify:
    branches:
      only:
        - master
